### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by AKGfra** [ShingekiNoRex/CW-FreeShop#1]
dont see ur plug in in BepinEx mods settings

Even if i drag ur mod in directory, items isn't free

**Comment by ShingekiNoRex** [comment]
The plugin doesn't have any config settings.
You can check BepinEX log to see if it's successfully loaded.
Item prices are not changed.  The plugin just removes the restriction for order and purchase, so that you can buy items on your will.

It's working for me even after the latest update. Feel free to reopen if the issue persists for you.
